// <auto-generated />
namespace BallingMaskiner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addededitmode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addededitmode));
        
        string IMigrationMetadata.Id
        {
            get { return "201605222006223_added editmode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
