// <auto-generated />
namespace BallingMaskiner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednullabletodatetimeproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednullabletodatetimeproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201605222109438_Added nullable to datetime property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
