// <auto-generated />
namespace BallingMaskiner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedFileDatamodelandQuotationreferencetofiledata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFileDatamodelandQuotationreferencetofiledata));
        
        string IMigrationMetadata.Id
        {
            get { return "201605211943401_Added FileData model and Quotation reference to filedata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
